 AFRAME.registerComponent('cursor-animator', {

init: function () {

     var currentEvent = "-start";
     var theVideo = document.querySelector('#fish');
     var On = document.querySelector('#on');
     var Off = document.querySelector('#off');
     var Pause = document.querySelector('#wait');

            this.el.addEventListener( 'click', function () {
            this.setAttribute('visible', "false");
            this.setAttribute('scale', "0 0");
            Pause.setAttribute('visible', "true");
            Pause.setAttribute('scale', "0.8 0.8");
            Off.setAttribute('visible', "true");
            theVideo.play();

         document.getElementById("ryba").setAttribute('animation__reverse', "autoplay", "true");
         document.getElementById("ryba").setAttribute('animation__hop', "autoplay", "true");
         document.getElementById("ryba").setAttribute('animation__turn', "autoplay", "true");
         document.getElementById("ryba").setAttribute('animation__hide', "autoplay", "true");
         document.getElementById("ryba").setAttribute('animation__show', "loop", "false");

         document.getElementById("type-1").emit('1' + currentEvent);
         document.getElementById("type-2").emit('2' + currentEvent);
         document.getElementById("type-3").emit('3' + currentEvent);
         document.getElementById("type-1").emit('4' + currentEvent);
         document.getElementById("type-4").emit('7' + currentEvent);
         document.getElementById("type-2").emit('5' + currentEvent);
         document.getElementById("type-3").emit('6' + currentEvent);
         document.getElementById("type-5").emit('8' + currentEvent);
         document.getElementById("type-6").emit('9' + currentEvent);
         document.getElementById("type-7").emit('10' + currentEvent);
         document.getElementById("type-8").emit('11' + currentEvent);
         document.getElementById("type-9").emit('12' + currentEvent);
         document.getElementById("type-4").emit('13' + currentEvent);
         document.getElementById("type-10").emit('19' + currentEvent);
         document.getElementById("type-5").emit('14' + currentEvent);
         document.getElementById("type-6").emit('15' + currentEvent);
         document.getElementById("type-7").emit('16' + currentEvent);
         document.getElementById("type-8").emit('17' + currentEvent);
         document.getElementById("type-9").emit('18' + currentEvent);
         document.getElementById("type-11").emit('20' + currentEvent);
         document.getElementById("type-12").emit('21' + currentEvent);
         document.getElementById("type-10").emit('22' + currentEvent);
         document.getElementById("type-13").emit('25' + currentEvent);
         document.getElementById("type-11").emit('23' + currentEvent);
         document.getElementById("type-12").emit('24' + currentEvent);
         document.getElementById("type-14").emit('26' + currentEvent);
         document.getElementById("type-15").emit('27' + currentEvent);
         document.getElementById("type-13").emit('28' + currentEvent);
         document.getElementById("type-16").emit('31' + currentEvent);
         document.getElementById("type-14").emit('29' + currentEvent);
         document.getElementById("type-15").emit('30' + currentEvent);
         document.getElementById("type-17").emit('32' + currentEvent);
         document.getElementById("type-18").emit('33' + currentEvent);
         document.getElementById("type-19").emit('34' + currentEvent);
         document.getElementById("type-16").emit('35' + currentEvent);
         document.getElementById("type-17").emit('36' + currentEvent);
        document.getElementById("type-18").emit('37' + currentEvent);
         document.getElementById("type-19").emit('38' + currentEvent);
        currentEvent = "-pause";
          });

    Pause.addEventListener( 'click', function () {
            Pause.setAttribute('visible', "false");
            Pause.setAttribute('scale', "0 0");
            On.setAttribute('visible', "true");
            On.setAttribute('scale', "0.2 0.2");
         document.getElementById("type-1").emit('1-pause');
         document.getElementById("type-2").emit('2-pause');
         document.getElementById("type-3").emit('3-pause');
         document.getElementById("type-1").emit('4-pause');
         document.getElementById("type-4").emit('7-pause');
         document.getElementById("type-2").emit('5-pause');
         document.getElementById("type-3").emit('6-pause');
         document.getElementById("type-5").emit('8-pause');
         document.getElementById("type-6").emit('9-pause');
         document.getElementById("type-7").emit('10-pause');
         document.getElementById("type-8").emit('11-pause');
         document.getElementById("type-9").emit('12-pause');
         document.getElementById("type-4").emit('13-pause');
         document.getElementById("type-10").emit('19-pause');
         document.getElementById("type-5").emit('14-pause');
         document.getElementById("type-6").emit('15-pause');
         document.getElementById("type-7").emit('16-pause');
         document.getElementById("type-8").emit('17-pause');
         document.getElementById("type-9").emit('18-pause');
         document.getElementById("type-11").emit('20-pause');
         document.getElementById("type-12").emit('21-pause');
         document.getElementById("type-10").emit('22-pause');
         document.getElementById("type-13").emit('25-pause');
         document.getElementById("type-11").emit('23-pause');
         document.getElementById("type-12").emit('24-pause');
         document.getElementById("type-14").emit('26-pause');
         document.getElementById("type-15").emit('27-pause');
         document.getElementById("type-13").emit('28-pause');
         document.getElementById("type-16").emit('31-pause');
         document.getElementById("type-14").emit('29-pause');
         document.getElementById("type-15").emit('30-pause');
         document.getElementById("type-17").emit('32-pause');
         document.getElementById("type-18").emit('33-pause');
         document.getElementById("type-19").emit('34-pause');
         document.getElementById("type-16").emit('35-pause');
         document.getElementById("type-17").emit('36-pause');
        document.getElementById("type-18").emit('37-pause');
         document.getElementById("type-19").emit('38-pause');
        currentEvent = "-resume";
        });

    Off.addEventListener( 'click', function () {
            theVideo.pause();
            theVideo.currentTime = 0;
            Off.setAttribute('visible', "false");
            Pause.setAttribute('visible', "false");
            On.setAttribute('visible', "true");
            On.setAttribute('scale', "0.2 0.2");
          document.getElementById("type-1").emit('1-pause');
         document.getElementById("type-2").emit('2-pause');
         document.getElementById("type-3").emit('3-pause');
         document.getElementById("type-1").emit('4-pause');
         document.getElementById("type-4").emit('7-pause');
         document.getElementById("type-2").emit('5-pause');
         document.getElementById("type-3").emit('6-pause');
         document.getElementById("type-5").emit('8-pause');
         document.getElementById("type-6").emit('9-pause');
         document.getElementById("type-7").emit('10-pause');
         document.getElementById("type-8").emit('11-pause');
         document.getElementById("type-9").emit('12-pause');
         document.getElementById("type-4").emit('13-pause');
         document.getElementById("type-10").emit('19-pause');
         document.getElementById("type-5").emit('14-pause');
         document.getElementById("type-6").emit('15-pause');
         document.getElementById("type-7").emit('16-pause');
         document.getElementById("type-8").emit('17-pause');
         document.getElementById("type-9").emit('18-pause');
         document.getElementById("type-11").emit('20-pause');
         document.getElementById("type-12").emit('21-pause');
         document.getElementById("type-10").emit('22-pause');
         document.getElementById("type-13").emit('25-pause');
         document.getElementById("type-11").emit('23-pause');
         document.getElementById("type-12").emit('24-pause');
         document.getElementById("type-14").emit('26-pause');
         document.getElementById("type-15").emit('27-pause');
         document.getElementById("type-13").emit('28-pause');
         document.getElementById("type-16").emit('31-pause');
         document.getElementById("type-14").emit('29-pause');
         document.getElementById("type-15").emit('30-pause');
         document.getElementById("type-17").emit('32-pause');
         document.getElementById("type-18").emit('33-pause');
         document.getElementById("type-19").emit('34-pause');
         document.getElementById("type-16").emit('35-pause');
         document.getElementById("type-17").emit('36-pause');
        document.getElementById("type-18").emit('37-pause');
         document.getElementById("type-19").emit('38-pause');
             document.getElementById("type-1").setAttribute('visible', "false");
             document.getElementById("type-2").setAttribute('visible', "false");
             document.getElementById("type-3").setAttribute('visible', "false");
             document.getElementById("type-4").setAttribute('visible', "false");
             document.getElementById("type-5").setAttribute('visible', "false");
             document.getElementById("type-6").setAttribute('visible', "false");
             document.getElementById("type-7").setAttribute('visible', "false");
             document.getElementById("type-8").setAttribute('visible', "false");
             document.getElementById("type-9").setAttribute('visible', "false");
             document.getElementById("type-10").setAttribute('visible', "false");
             document.getElementById("type-11").setAttribute('visible', "false");
             document.getElementById("type-12").setAttribute('visible', "false");
             document.getElementById("type-13").setAttribute('visible', "false");
             document.getElementById("type-14").setAttribute('visible', "false");
             document.getElementById("type-15").setAttribute('visible', "false");
             document.getElementById("type-16").setAttribute('visible', "false");
             document.getElementById("type-17").setAttribute('visible', "false");
             document.getElementById("type-18").setAttribute('visible', "false");
             document.getElementById("type-19").setAttribute('visible', "false");
        currentEvent = "-start";

        });

 }

      });
